export const JOBREQUEST_FETCH = "JOBREQUEST/FETCH";
export const JOBREQUEST_INSERT = "JOBREQUEST/INSERT";
export const JOBREQUEST_UPDATE = "JOBREQUEST/UPDATE";
export const JOBREQUEST_DELETE = "JOBREQUEST/DELETE";
export const RESET_STATUS = "RESET_STATUS";

