export const INTERVIEW_FETCH = "INTERVIEW/FETCH";
export const INTERVIEW_INSERT = "INTERVIEW/INSERT";
export const INTERVIEW_UPDATE = "INTERVIEW/FETCH";
export const INTERVIEW_DELETE = "JOBREQUEST/DELETE";

