const users = [
  {
    id: 1,
    name: "Vũ Quốc Luật",
    employee_code: "PH12182",
    email: "luatvqph12182@fpt.edu.vn",
    role: 1,
    status: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 2,
    name: "Hoang Van Anh",
    employee_code: "PH12352",
    email: "anhhvph12352@fpt.edu.vn",
    role: 3,
    status: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 3,
    name: "Tran The Cuong",
    employee_code: "PHxxxxx",
    email: "cuongttphxxxxx@fpt.edu.vn",
    role: 2,
    status: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 4,
    name: "Nguyen Thi My",
    employee_code: "PH12144",
    email: "myntph12144@fpt.edu.vn",
    role: 0,
    status: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 5,
    name: "Duong Thi Huong Sen",
    employee_code: "PHxxxxx",
    email: "Sendthphxxxxx@fpt.edu.vn",
    role: 3,
    status: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 9,
    name: "Duong Thi Huong Sen",
    employee_code: "PHxxxxx",
    email: "Sendthphxxxxx@fpt.edu.vn",
    role: 3,
    status: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 6,
    name: "User demo 1",
    employee_code: "PHxxxxx",
    email: "userDemo1xxxxx@fpt.edu.vn",
    role: 3,
    status: 1,
    created_at: null,
    updated_at: null,
  },
  {
    id: 7,
    name: "User demo 2",
    employee_code: "PHxxxxx",
    email: "userDemo2xxxx@fpt.edu.vn",
    role: 2,
    status: 0,
    created_at: null,
    updated_at: null,
  },
  {
    id: 8,
    name: "User demo 3",
    employee_code: "PHxxxxx",
    email: "userDemo3xxxx@fpt.edu.vn",
    role: 2,
    status: 1,
    created_at: null,
    updated_at: null,
  },
];

export const fakeApiGetUser = () => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(users);
    }, 1500);
  });
};
